# Generated by Django 2.1.7 on 2019-02-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190220_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='discription',
            new_name='summary',
        ),
    ]
