# Generated by Django 2.1.7 on 2019-02-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190222_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summary',
            new_name='discription',
        ),
    ]
